/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'analytics': RouteRecordInfo<'analytics', '/analytics', Record<never, never>, Record<never, never>>,
    'categories': RouteRecordInfo<'categories', '/categories', Record<never, never>, Record<never, never>>,
    'company': RouteRecordInfo<'company', '/company', Record<never, never>, Record<never, never>>,
    'grades': RouteRecordInfo<'grades', '/grades', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'modules': RouteRecordInfo<'modules', '/modules', Record<never, never>, Record<never, never>>,
    'permissions': RouteRecordInfo<'permissions', '/permissions', Record<never, never>, Record<never, never>>,
    'points': RouteRecordInfo<'points', '/points', Record<never, never>, Record<never, never>>,
    'positions': RouteRecordInfo<'positions', '/positions', Record<never, never>, Record<never, never>>,
    'schools': RouteRecordInfo<'schools', '/schools', Record<never, never>, Record<never, never>>,
    'schools-create': RouteRecordInfo<'schools-create', '/schools/create', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'students': RouteRecordInfo<'students', '/students', Record<never, never>, Record<never, never>>,
    'students-import': RouteRecordInfo<'students-import', '/students/import', Record<never, never>, Record<never, never>>,
    'subjects': RouteRecordInfo<'subjects', '/subjects', Record<never, never>, Record<never, never>>,
    'super-admin-dashboard': RouteRecordInfo<'super-admin-dashboard', '/super-admin/dashboard', Record<never, never>, Record<never, never>>,
    'teachers': RouteRecordInfo<'teachers', '/teachers', Record<never, never>, Record<never, never>>,
    'teachers-import': RouteRecordInfo<'teachers-import', '/teachers/import', Record<never, never>, Record<never, never>>,
    'unauthorized': RouteRecordInfo<'unauthorized', '/unauthorized', Record<never, never>, Record<never, never>>,
    'user-points': RouteRecordInfo<'user-points', '/user-points', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'users-admin': RouteRecordInfo<'users-admin', '/users/admin', Record<never, never>, Record<never, never>>,
    'values': RouteRecordInfo<'values', '/values', Record<never, never>, Record<never, never>>,
  }
}
